//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_projects
    {
        public todo_projects()
        {
            this.todo_todo = new HashSet<todo_todo>();
        }
    
        public string project_id { get; set; }
        public string project_name { get; set; }
    
        public virtual ICollection<todo_todo> todo_todo { get; set; }
    }
}
