//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class todosEntities : DbContext
    {
        public todosEntities()
            : base("name=todosEntities")
           // : base("server=localhost;user id=root;database=awesome_todos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<todo_projects> todo_projects { get; set; }
        public DbSet<todo_projects_statuses> todo_projects_statuses { get; set; }
        public DbSet<todo_statuses> todo_statuses { get; set; }
        public DbSet<todo_todos> todo_todos { get; set; }
        public DbSet<v_todos> v_todos { get; set; }
    }
}
