//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_logs
    {
        public string log_id { get; set; }
        public string user_id { get; set; }
        public string event_id { get; set; }
        public string field_name { get; set; }
        public string data_id { get; set; }
        public string action_name { get; set; }
        public System.DateTime added_on { get; set; }
    
        public virtual todo_events todo_events { get; set; }
        public virtual todo_users todo_users { get; set; }
    }
}
