//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_todos
    {
        public todo_todos()
        {
            this.todo_projects_todos = new HashSet<todo_projects_todos>();
            this.todo_todos_statuses = new HashSet<todo_todos_statuses>();
            this.todo_users_todos = new HashSet<todo_users_todos>();
        }
    
        public string todo_id { get; set; }
        public string issue_number { get; set; }
        public string todo_text { get; set; }
        public string is_active { get; set; }
    
        public virtual ICollection<todo_projects_todos> todo_projects_todos { get; set; }
        public virtual ICollection<todo_todos_statuses> todo_todos_statuses { get; set; }
        public virtual ICollection<todo_users_todos> todo_users_todos { get; set; }
    }
}
