//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_projects
    {
        public todo_projects()
        {
            this.todo_todos = new HashSet<todo_todos>();
        }
    
        public string project_id { get; set; }
        public string project_name { get; set; }
        public string is_active { get; set; }
    
        public virtual ICollection<todo_todos> todo_todos { get; set; }
    }
}
