//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_events
    {
        public todo_events()
        {
            this.todo_logs = new HashSet<todo_logs>();
        }
    
        public string event_id { get; set; }
        public string event_code { get; set; }
        public string event_name { get; set; }
    
        public virtual ICollection<todo_logs> todo_logs { get; set; }
    }
}
