//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_todos_statuses
    {
        public string todo_status_id { get; set; }
        public string todo_id { get; set; }
        public string status_id { get; set; }
        public System.DateTime added_on { get; set; }
        public string is_latest { get; set; }
    
        public virtual todo_statuses todo_statuses { get; set; }
        public virtual todo_todos todo_todos { get; set; }
    }
}
