//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.mysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_users
    {
        public todo_users()
        {
            this.todo_projects = new HashSet<todo_projects>();
        }
    
        public string user_id { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
        public string user_fullname { get; set; }
    
        public virtual ICollection<todo_projects> todo_projects { get; set; }
    }
}
